### ISSUE TITLE
gamipress/includes/scripts.php:124 | 'rewards-calendar'

### ISSUE THREAD

**Issue by altechzilla** [rubengc/GamiPress#10]
In order to support the Daily Login Rewards addon, you need to add the 'rewards-calendar' to the post types list on gamipress/includes/scripts.php:124. Otherwise when you're in the admin area, scripts won't load and the rewards achievements dropdowns won't lazy load the options.

**Comment by altechzilla** [comment]
I would suggest adding a filter and having the add-ons extend that filter with their own post types.

**Comment by rubengc** [comment]
Hi @altechzilla 

For pro add-on issues, contact us through this form:
https://gamipress.com/contact-us/

Best regards
