### ISSUE TITLE
[feature request] Automatically revoke achievement after given period of time

### ISSUE THREAD

**Issue by maciejkwas** [rubengc/GamiPress#12]
I'd like to propose a feature where you are able to create an achievement that is automatically revoked after specific period of time (eg. after 30 days), would be useful on special occasions like short events or holidays time.

**Comment by rubengc** [comment]
Hi @maciejkwas 

Thank you so much for your interest on GamiPress and suggestion, we will keep it in mind for future add-ons

Best regards
