### ISSUE TITLE
Problem with block_categories

### ISSUE THREAD

**Issue by omhabibal** [rubengc/GamiPress#17]
Hello 
in includes/blocks.php LINE 29

```php
add_filter( 'block_categories', 'gamipress_register_block_categories', 10, 2 );
add_filter( 'block_categories_all', 'gamipress_register_block_categories', 10, 2 `);`
```

```php
if ( version_compare( $wordpress_version, '5.8-beta0', '<' ) ) {
	// 5.8+, context is 2nd parameter.
	add_filter( 'block_categories_all', 'gamipress_register_block_categories', 10, 2 );
} else {
	// Pre-5.8, post is 2nd parameter.
	add_filter( 'block_categories', 'gamipress_register_block_categories, 10, 2 );
 }
```

I think the correct code is it right?

Because I have a issus on my dashboard anyone confirming me ? because when I use on LMS Leardash I have a Sue Tobic error that tells me that:

```
Deprecated: block_categories est obsolète depuis la version 5.8.0 ! Utilisez block_categories_all à la place. in /home/website.com/wp-includes/functions.php on line 5586
Deprecated: block_categories est obsolète depuis la version 5.8.0 ! Utilisez block_categories_all à la place. in /home/website.com/wp-includes/functions.php on line 5586
```

WORDPRESS Version 5.8.2 MULTISITE 
Plugin : learndash , GamiPress, PeepSo , Paid Memberships Pro, WooCommerce 
Cordially

**Comment by rubengc** [comment]
Thank you so much for report this issue and provide a possible solution!

We will release a fix in the next update to prevent this message

Note: This message is not an error, simply a developer message from WordPress alerting that a hook is deprecated from 5.8 version
