### ISSUE TITLE
[Feature Request] Allow searching by Post ID

### ISSUE THREAD

**Issue by pryley** [rubengc/GamiPress#19]
I am building a Gamipress integration for the [Site Reviews](https://wordpress.org/plugins/site-reviews/) plugin.

Some of the triggers required a user selector, so I've added one. 

I have allowed searching by both User display_name and User ID because some community websites have a lot of users and the display names are not always unique. Here is an example of the user selector in use:

https://user-images.githubusercontent.com/134939/154189744-597bd0f3-218c-4b60-8bf2-4277993697f7.mp4

I think it might be useful to allow searching for posts in the same way (i.e. by Post ID and post_title). There are probably cases where a website has a lot of posts with similar titles, or similar product names, etc. Currently it is not possible to search by a specific Post ID as shown in this example: 

https://user-images.githubusercontent.com/134939/154190009-932e9919-4791-42d9-8f66-68fa3c4ad0d6.mp4

This is how I am doing it with the user selector:

```php
    /**
     * @return void
     * @action wp_ajax_site_reviews_gamipress/users
     */
    public function fetchUsers()
    {
        check_ajax_referer('gamipress_admin', 'nonce');
        global $wpdb;
        $limit = 20;
        $paged = Helper::ifEmpty(absint(filter_input(INPUT_POST, 'page')), 1, true);
        $offset = $limit * ($paged - 1);
        $searchId = '%%'.absint(filter_input(INPUT_POST, 'q')).'%%';
        $searchName = '%%'.$wpdb->esc_like(trim(filter_input(INPUT_POST, 'q'))).'%%';
        $results = $wpdb->get_results($wpdb->prepare("
            SELECT ID, display_name 
            FROM {$wpdb->users}
            WHERE (display_name LIKE %s OR ID LIKE %s)
            ORDER BY display_name ASC 
            LIMIT {$offset}, {$limit}
        ", $searchName, $searchId));
        $count = absint($wpdb->get_var($wpdb->prepare("
            SELECT COUNT(*)
            FROM {$wpdb->users}
            WHERE (display_name LIKE %s OR ID LIKE %s)
        ", $searchName, $searchId)));
        wp_send_json_success([
            'results' => $results,
            'more_results' => $count > $limit && $count > $offset,
        ]);
    }
```

**Comment by rubengc** [comment]
Hi @pryley 

Thank you so much for your suggestion!

Definitely is a great addition to this selector so I just added it to our roadmap for our posts and users selectors
