### ISSUE TITLE
PHP Notice:  Undefined variable

### ISSUE THREAD

**Issue by younes-dro** [rubengc/GamiPress#22]
Hello GamiPress Team,

I am developing a GamiPress Add-on, I find this notice repetitive
`[07-Nov-2022 12:17:05 UTC] PHP Notice:  Undefined variable: earning in C:\wamp64\www\expresstechsoftware-gamipress\wp-content\plugins\gamipress\includes\rules-engine.php on line 1702`

**Comment by rubengc** [comment]
Hi @younes-dro 

Thank you so much for report this notice, I just address it to the team and will get fixed in next update!
