### ISSUE TITLE
Multisite inconsistencies with NO network-wide activation

### ISSUE THREAD

**Issue by tambaqui** [rubengc/GamiPress#23]
Hi,

GamiPress is not registering earnings correctly when in a multisite installation it is enabled independently for each site, that is, without activating it at the network level, if the same slugs are used for points, badges or ranks CPTs in the different sites.

At log and earnings level, in the specific GamiPress tables for each site (`wp_gamipress_logs`, `wp_gamipress_user_earnings`,...) everything works correctly, since each site has its own tables. But the earnings registered in `wp_usermeta` table are not recorded independently for each site but globally, so if two sites use the **same slugs** they **conflict** so that the points are added between sites and ranks are overwritten.

### Sample context:

We start from a multisite installation with 3 sites (A, B and C).
User X belongs to all 3 sites.

Sites A and B use the same point and rank system (with the same slugs):
- "coin" slug for points type
- "level" slug for rank type

Site C uses a different system of points and ranks (with different slugs):
- "stone" slug for points type
- "position" slug for rank type

Initial situation of user X:

Site A: 0 coins, level 1
Site B: 0 coins, level 1
Site C: 0 stones, position 1

Next, I perform the following actions via GamiPress > Tools > Bulk Awards:
- On site A I give 25 coins to user X.
- On site B I give 15 coins and level 2 to user X.
- On site C I give 30 stones and position 3 to user X.

In the frontend I include the **gamipress_user_rank** and **gamipress_points** shortcodes with these settings:

Sites A and B:
```
[gamipress_user_rank type="level" prev_rank="no" current_rank="yes" next_rank="no" current_user="yes"]
[gamipress_points type="coin" label="no" current_user="yes"]
```

Site C:
```
[gamipress_user_rank type="position" prev_rank="no" current_rank="yes" next_rank="no" current_user="yes"]
[gamipress_points type="stone" label="no" current_user="yes"]
```

The expected result should be the following:

Site A: 25 coins, level 1
Site B: 15 coins, level 2
Site C: 30 stones, position 3

But the result obtained is the following:

Site A: 40 coins, level 2
Site B: 40 coins, level 2
Site C: 30 stones, position 3

That is, Site C is working correctly because it uses different slugs, but Site A and B are conflicting, their points are added up, and their rankings are overwritten.

In this sense, the ranks are more problematic, since GamiPress saves in `wp_usermeta` in the key `_gamipress_level_rank` the post_id of the post corresponding to the level assigned on the site from which it is granted, but that id does not have to exist on other sites or could even correspond to a different level. For example:
- If level 2 has post_id = 7 on site A and there is no level with post_id = 7 on site B, the gamipress_user_rank widget does not show any Level on site B.
- If level 2 has post_id = 7 on site A and on site B the post_id = 7 corresponds to level 3, the gamipress_user_rank widget shows Level 3 disabled on site B.

I think the problem is in the helper functions that manage user metadata (`gamipress_get_user_meta`, `gamipress_update_user_meta` and `gamipress_delete_user_meta`) that do not take into account a multisite installation with `gamipress_is_network_wide_active() = false`.

So for example, the current implementation of `gamipress_update_post_meta` is the following:

```php
function gamipress_update_user_meta( $user_id, $meta_key, $meta_value, $prev_value = '' ) {

     if( gamipress_is_network_wide_active() ) {
         return update_user_option( $user_id, $meta_key, $meta_value, true );
     } else {
         return update_user_meta( $user_id, $meta_key, $meta_value, $prev_value );
     }

}
```

Basically the same action is being performed in both the if and the else, saving the user meta without site prefix.

The correct implementation should be something like this:

```php
function gamipress_update_user_meta( $user_id, $meta_key, $meta_value, $prev_value = '' ) {

     if( gamipress_is_network_wide_active() ) {
         return update_user_option( $user_id, $meta_key, $meta_value, true );
     } else {
         return update_user_option( $user_id, $meta_key, $meta_value, false );
     }

}

```
So it works both in a multisite installation with `gamipress_is_network_wide_active() = false` and in a single site installation, since update_user_option with `$global = false`  (default value) will save the key with the site prefix in a multisite installation and without prefix in a single site installation.

The `gamipress_get_user_meta` and `gamipress_delete_user_meta` helper functions require a similar solution.

I do not know if this change may have other implications.

All the best.

**Comment by rubengc** [comment]
Hi @tambaqui 

The user meta functions are correct because when GamiPress is active network wide is required to use the user_option instead the user_meta to have everything centralized

At the end of this page, you can find a snippet to override the workflow of the network wide active function:
https://gamipress.com/docs/advanced/multisite/

Have you tried to place that snippet in all your sites and subsites?

**Comment by tambaqui** [comment]
Hi @rubengc,

Yes, I have tried the filter "gamipress_disable_network_data_centralization" but it has no effect. Data is always saved centrally regardless of whether you activate GamiPress at the network level or not.

In my case I do NOT have GamiPress activated at the network level, but independently for each site, so everything should be independent and it is not the case.

I think you are confused regarding the purpose of user_option vs user_meta. You have to take into account that in a multisite installation there is only one `wp_usermeta` table for the whole network and both user_option and user_meta save the data in that table. There is not a `wp_x_usermeta` table for every site.

The `update_user_option` function is simply a wrapper around `update_user_meta`, only it has global support, and if you pass the value true in the $global parameter it does exactly the same thing as update_user_meta . This is why the gamipress_update_user_meta function is incorrect, since you are doing exactly the same thing in the if and in the else:

These actions:
```
update_user_option( $user_id, $meta_key, $meta_value, true );
update_user_meta( $user_id, $meta_key, $meta_value, $prev_value );
```
Are equivalent, they both do the same thing, save the meta without site prefix. Therefore, if GamiPress is activated at the network level and you want to save the data centrally, you can use either of the two in the if. But the else is incorrect, since if GamiPress is not activated at the network level and therefore you want the data to be independent for each site, you need the metadata to be registered with the site prefix, and therefore you must use the update_user_option there with the $global parameter to false. That is, in the else it has to go yes or yes:

`update_user_option( $user_id, $meta_key, $meta_value, false );`

In fact, currently GamiPress, due to this confusion, is also not working well if we activate it at the network level with the filter:

`add_filter( 'gamipress_disable_network_data_centralization', '__return_true' );`

Although it is not my case since I have it disabled at the network level. In any case, let me explain:

If I activate gamipress at the network level, regardless of the filter or the gamipress network option "Show achievements earned across all sites on the network" is active or not, earnings are always recorded and displayed globally for all sites of the network.

With filter "gamipress_disable_network_data_centralization" the behavior is, to say the least, disconcerting:

**On the main site:**

In the backend area I can see the point types, rank types and ranks for created rank types.
Iin the frontend the "gamipress_user_rank" and "gamipress_points" widgets are displayed correctly.

**On secondary sites:**

In the backend area there are neither point types nor rank types, but in Ranks it shows me the rank created for the main site (level) without values, and although I can add values it has no effect. 
In frontend the "gamipress_points" widget shows the global points, while the "gamipress_user_rank" widget is not shown and generates warnings:
Warning: Attempt to read property “ID” on null in \plugins\gamipress\includes\template-functions.php on line 102
Warning: Attempt to read property “post_type” on null in \plugins\gamipress\includes\template-functions.php on line 99
Warning: Attempt to read property “ID” on null in \plugins\gamipress\includes\functions\ranks.php on line 851

If in this situation I try to create in the secondary sites the same rank type (level) as in the main site, I can't since Gamipress won't let me use the same slug showing the message "The Level post type already uses this slug.". If I create another rank type with a different slug (position) it lets me create it, but it doesn't appear in Ranks and therefore I can't create ranks associated with that rank type. The widget does not work in any case.

That is, with gamipress enabled at the network level and the "gamipress_disable_network_data_centralization" filter enabled, I can't use ranks on the secondary sites in any way, only on the main site.

**Comment by rubengc** [comment]
Hi @tambaqui 

Finally found the issue and fixed in 2.5.0

Thank you so much for your report and for help us make GamiPress better!

**Comment by tambaqui** [comment]
Thanks @rubengc, I will test it thoroughly next year ;)

**Comment by rubengc** [comment]
You're welcome @tambaqui 

Happy holidays and happy new year!

**Comment by tambaqui** [comment]
Hi @rubengc, 
Happy new Year!

I have been testing the new version and earnings registration works correctly allowing the independence of the sites, thank you very much.

There is some inconsistency when we show the list of winners with the shortcodes [gamipress_ranks] and [gamipress_rank], I review it a bit and open another issue.

**Comment by rubengc** [comment]
Great @tambaqui glad to know! and yes please, feel free to report anything you find
