### ISSUE TITLE
Rank earners not displayed correctly in multisite

### ISSUE THREAD

**Issue by tambaqui** [rubengc/GamiPress#25]
Hi,

I open a new issue, since the problem of #24, in relation to point 2. Display earners, persists after updating to the latest version of Gamipress 2.5.7.1.

Rank earners are not displayed correcly in multisite with NO network-wide activation.

I attach some quick tests in a clean site comparing how the shortcodes `gamipress_ranks` and `gamipress_achievements` behave in relation to earners:

### 1. Gamipress Ranks Earners (INCORRECT results):

Shortcode config:
`[gamipress_ranks type="rank" orderby="priority" order="ASC" columns="3" title_size="h3" earners="yes" earners_limit="5" layout="top" align="center" link="yes" requirements="no"]`

Animated gif:
![ranks_multisite](https://user-images.githubusercontent.com/1532906/220161185-207e72d1-5c2c-4bb6-85e7-018cbb6bfd96.gif)

### 2. Gamipress Achievements Earners (CORRECT results):

Shortcode config:
`[gamipress_achievements type="badge" filter="no" search="no" columns="3" title_size="h3" steps="no" points_awarded="no" toggle="no" unlock_button="no" times_earned="no" global_times_earned="no" earners="yes" earners_limit="7" layout="top" align="center" link="yes" current_user="yes"]`

Animated gif:
![achievements_multisite](https://user-images.githubusercontent.com/1532906/220161407-5d48bfb6-a57a-4deb-895e-21f0f75be2fb.gif)

Regards!

**Comment by tambaqui** [comment]
Hi, any news about this issue? it is important for my project to show the rank earners correctly.

**Comment by tambaqui** [comment]
Hi, reviewing the code I think that the problem could be located in the `gamipress_get_rank_earners` method. Here the meta_key is being used in the query without site prefix, when the data is being saved with a site prefix if it is multisite and not network wide active:

```php
...

$meta = '_gamipress_rank';

if( ! empty( $rank_type ) ) {
      $meta = "_gamipress_{$rank_type}_rank";
}

// Setup vars
$from = "{$wpdb->usermeta} AS u ";
$where = "u.meta_key = '{$meta}' AND u.meta_value = '{$rank_id}' ";

...
```

Posible fix:

```php
...

$meta = '_gamipress_rank';

if( ! empty( $rank_type ) ) {
      $meta = "_gamipress_{$rank_type}_rank";
}

if ( is_multisite() && ! gamipress_is_network_wide_active() ) {
      $meta = $wpdb->get_blog_prefix() . $meta;
}

// Setup vars
$from = "{$wpdb->usermeta} AS u ";
$where = "u.meta_key = '{$meta}' AND u.meta_value = '{$rank_id}' ";

...
```

**Comment by rubengc** [comment]
Hi @tambaqui and sorry for the delay here

We released an new update yesterday fixing this issue, please update GamiPress and check if with latest version this issue has been resolved

**Comment by tambaqui** [comment]
Thanks @rubengc , it works correctly now.
