### ISSUE TITLE
WPMU User Update Remove Cover Listener Error

### ISSUE THREAD

**Issue by tambaqui** [rubengc/GamiPress#29]
Hi, 
There is a little problem with the Listeners of the WP_User_Manager plugin. 
The `wpum_user_update_remove_cover` action hook of the WP_User_Manager plugin only sends the $user_id as a parameter, but in gamipress this hook it is declared expecting 2 parameters: $user_id and $image_url, which causes a PHP Fatal Error:

```
PHP Fatal error: Uncaught ArgumentCountError: Too few arguments to function gamipress_wp_user_manager_remove_cover(), 1 passed in /wp-includes/class-wp-hook.php on line 324 and exactly 2 expected in /wp-content/plugins/gamipress/integrations/wp-user-manager/includes/listeners.php:150
```

**Comment by rubengc** [comment]
Thanks @tambaqui for reporting this issue!

Our team just fixed it in the latest update

**Comment by tambaqui** [comment]
Un placer @rubengc ;)
