### ISSUE TITLE
H5P points per score user meta not reset when reset logs and earnings

### ISSUE THREAD

**Issue by tambaqui** [rubengc/GamiPress#30]
Hi,
I'm using the Gamipress - H5P Points Per Score addon plugin to award points to users based on their H5P multiple choice content results, by checking the "Award only one time" option.
The problem I have is that if I reset the user logs and earnings using the Gamipress "Reset Data" tool, although the logs and earnings are deleted correctly, there are still some meta in the `wp_user_meta` table that prevent the user from getting the points again if they perform the H5P multiple choice again. Specifically, after the reset, the `_gamipress_h5p_points_per_score_[point]_[h5p_content_id]_awarded` meta remains in the `wp_user_meta` table, so the user cannot earn those points again.
Is there any way for the logs and earnings reset to delete that meta as well?

Thanks

**Comment by rubengc** [comment]
Hi @tambaqui 

The Reset Data tool included in GamiPress only will reset the options selected in the tool, is not designed to reset everything, to reset all the data, there is a free plugin that lets you reset all the data to the user of your choice:
https://gamipress.com/add-ons/reset-user/
