### ISSUE TITLE
$old_rank doesn't get populate

### ISSUE THREAD

**Issue by raghavnarang** [rubengc/GamiPress#6]
As you can check the code in this link:
https://github.com/rubengc/GamiPress/blob/cd8290f7837cd4cc206ad3f088004e95bfdfdf19/includes/functions/ranks.php#L627

$old_rank is never getting populating in **gamipress_update_user_rank** function, due to $rank_type parameter is not passed.

**Comment by rubengc** [comment]
Thanks for your report @raghavnarang 

I just added a fix to this issue, on the wordpress.org will take a while get it applied but meanwhile, this repo is ready to get installed as a beta version

Best regards

**Comment by raghavnarang** [comment]
Thanks a lot @rubengc . GamiPress rocks.
