### ISSUE TITLE
Integration with Tutor LMS - quiz triggers do not work

### ISSUE THREAD

**Issue by ziobron** [rubengc/GamiPress#7]
I'm using a Tutor LMS add-on and it does not award any points for completing / passing / failing quizzes. 
It works with lessons and courses (with the same configuration).
Tested with about 50 students.

![Zrzut ekranu 2020-05-15 o 11 27 20](https://user-images.githubusercontent.com/4595135/82034872-108f1380-969f-11ea-9de4-f845cb7f46e4.png)

**Comment by ziobron** [comment]
GamiPress 1.8.4.8
GamiPress - Tutor LMS integration 1.0.2

**Comment by rubengc** [comment]
Hi @ziobron 

I have tested all the quiz events and all of them are working correctly

It users the Tutor action 'tutor_quiz_finished' located at tutor/classes/Quiz.php in case it could help you to better debug your issue, but like your other report, probably this issue could come from a conflict with another plugin or you actual theme

Best regards
