### ISSUE TITLE
Add Step / Add New Rank Requirement buttons do not work

### ISSUE THREAD

**Issue by ziobron** [rubengc/GamiPress#8]
Add Step button for Archievements does not work. Console log says:

```
ReferenceError: Can't find variable: gamipress_add_requirement
onclick — post.php:640
Zaznaczony element
<input style="margin-right: 1em" class="button" type="button" onclick="gamipress_add_requirement( this, 1305, 'step');" value="Add New Step">
```

![Zrzut ekranu 2020-05-15 o 11 34 19](https://user-images.githubusercontent.com/4595135/82035650-16d1bf80-96a0-11ea-8f3d-7ae9ae9c485f.png)

It also doesn't work for ranks with this error:

```
[Error] ReferenceError: Can't find variable: gamipress_add_requirement
	onclick (post.php:872)
> Zaznaczony element
< <input style="margin-right: 1em" class="button" type="button" onclick="gamipress_add_requirement( this, 985, 'rank-requirement');" value="Add New Rank Requirement">
```

 It works for points, however.

GamiPress 1.8.4.8 (but wasn't working also with 1.8.4.7)

**Comment by rubengc** [comment]
Hi @ziobron 

Looks like the issue is that the GamiPress admin scripts can't get enqueued for some reason on your site, and the most probable is that comes from a conflict with your theme or a plugin

Have you tried to perform a conflict test by switching to a default theme and by deactivating non GamiPress plugins?

Also, the message "Zaznaczony element" doesn't comes from GamiPress

**Comment by ziobron** [comment]
Hi @rubengc 

"Zaznaczony element" means just "Selected element" and it was Add new step button. 
Thanks for suggestion, I have figured out that when I disable two plugins it starts working.
They are:
- Qubely - Advanced Gutenberg Blocks
- Edumax Core

I use Tutor LMS Pro with Edumax theme and they were in one bundle. I will try to work without them.

**Comment by rubengc** [comment]
Hi @ziobron 

Then you should contact their authors to let them know about this issue, because for sure any team is interested on fix any conflict issue caused by their software

Best regards
