### ISSUE TITLE
Add the ability to pull only rank earner IDs instead of full objects.

### ISSUE THREAD

**Issue by altechzilla** [rubengc/GamiPress#9]
For performance reasons, it would be great if there was a `gamipress_get_rank_earners_ids` function that only pulls the rank earner user IDs when building custom integrations. 

Then it could be referenced inside `gamipress_get_rank_earners` to keep it clean.

**Comment by rubengc** [comment]
Hi @altechzilla 

For this purpose you have the `gamipress_get_achievement_earners( $achievement_id, $args )` that is able to return the earners of any achievement, rank or included achievement steps and rank requirements

Hope it helps

Best regards

**Comment by rubengc** [comment]
Also, I forgive to mention that you have the `gamipress_get_rank_earners( $rank_id, $args )` that is able to return users on the current rank

gamipress_get_achievement_earners() returns all users who have earned it
While gamipress_get_rank_earners() returns only users who have actually in this rank

Best regards
